-- Create the reported_issues table
CREATE TABLE IF NOT EXISTS reported_issues (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingId BIGINT REFERENCES bookings(Id),
    CustomerId UUID REFERENCES users(id),
    ChefId UUID REFERENCES users(id), -- Assuming chefs are also in the users table or similar
    IssueDescription TEXT,
    ReportedAt TIMESTAMPTZ DEFAULT NOW(),
    Status TEXT DEFAULT 'OPEN' -- OPEN, RESOLVED, etc.
);
