-- Drop the table if it exists (to fix any lowercase/bad schema attempts)
DROP TABLE IF EXISTS reported_issues;
DROP TABLE IF EXISTS "reported_issues";

-- Create the reported_issues table with PascalCase columns to match existing naming convention
CREATE TABLE "reported_issues" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookingId" BIGINT REFERENCES "bookings"("Id"),
    "CustomerId" UUID REFERENCES "users"("Id"),
    "ChefId" UUID REFERENCES "users"("Id"),
    "IssueDescription" TEXT,
    "ReportedAt" TIMESTAMPTZ DEFAULT NOW(),
    "Status" TEXT DEFAULT 'OPEN'
);
