-- Drop table if exists to ensure clean state during dev
DROP TABLE IF EXISTS "ratings" CASCADE;

-- Create the ratings table
CREATE TABLE "ratings" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookingId" BIGINT REFERENCES "bookings"("Id") ON DELETE CASCADE,
    "RaterId" UUID REFERENCES "users"("Id"),
    "RateeId" UUID REFERENCES "users"("Id"),
    "Rating" INTEGER CHECK ("Rating" >= 1 AND "Rating" <= 5),
    "Review" TEXT,
    "CreatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Add index for faster lookups
CREATE INDEX "idx_ratings_ratee" ON "ratings"("RateeId");
CREATE INDEX "idx_ratings_booking" ON "ratings"("BookingId");
